import type { Metadata } from "next";
import "./globals.css";
import '../style/imports.css';
import localFont from "next/font/local";

const bernier = localFont({
  src: "../public/font/BERNIERDISTRESSED-REGULAR.woff2",
  variable: "--font-bernier",
  weight: "400",
  display: "swap",
});

const ptSans = localFont({
  src: [
    { path: "../public/font/PTSans-Regular.ttf", weight: "400", style: "normal" },
    { path: "../public/font/PTSans-Bold.ttf", weight: "700", style: "normal" },
    { path: "../public/font/PTSans-Italic.ttf", weight: "400", style: "italic" },
    { path: "../public/font/PTSans-BoldItalic.ttf", weight: "700", style: "italic" },
  ],
  variable: "--font-ptsans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bernier.variable} ${ptSans.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
